### ISSUE TITLE
[Feature request]: Auto shutdown lights

### ISSUE THREAD

**Issue by lordraiden** [sblantipodi/firefly_luciferin#102]
### Is your feature request related to a problem? Please describe

I have my led board always power on. I would like that in case my computer is inactive (screen saver), or is going to be shutdown the the lights regarding the mode should go off.
The light should come back to the previous state after recovering from the screen saver.

There is a energy saving option but I think it only works when the dynamic lightning is enable, not with fixed modes.

**Comment by sblantipodi** [comment]
> There is a energy saving option but I think it only works when the dynamic lightning is enable, not with fixed modes.

Hi,
yes, this is how it works currently. 

When the bias light (dynamic lightning) is off Firefly stops capturing the screen so it's not aware if something is moving on the screen... 
I would not capture the screen when dynamic lightning is off just to check if the PC is in idle because screen capturing consumes a little bit of resources.
When screen capture is off, firefly should not consume resources.

I'll think on a better way to do it. feel free to share ideas :)

thanks
Davide

**Comment by lordraiden** [comment]
I know but I would like firefly to be able to shutdown the lights regardless de mode. So if the screen saver is on or the pc is going to be shutdown firefly should shut off the lights.

**Comment by lordraiden** [comment]
Hi @sblantipodi I have seen your pull here
https://github.com/sblantipodi/firefly_luciferin/pull/103

_If power saving option is enabled, Luciferin now turns off the lights when you shut down your PC or when the screen saver is active. (Closes https://github.com/sblantipodi/firefly_luciferin/issues/102)_

But my question is, it will shutdown the lights as well even if bias (dynamic light) is not enable? Many times times I use the leds in static mode only.

In any case thanks for the effort, I hope you can finish the new version soon.
