### ISSUE TITLE
Dual screen support

### ISSUE THREAD

**Issue by lroubinov** [sblantipodi/firefly_luciferin#27]
Is there a possibility to use it with dual extended screen?

**Comment by sblantipodi** [comment]
@lroubinov yes it works ok

**Comment by lroubinov** [comment]
the firefly application capture only the main screen in my pc
Am I doing something worng?

**Comment by sblantipodi** [comment]
sorry I haven't understood that you want to drive Luciferin on both monitors at the same time.
no, currently Luciferin does not support multi monitor configuration but I will add this feature in the next future.

I am going to close this issue for now because adding multi monitor support is on the schedule but not on the very first one for now.

feel free to open other issues or comment here if you have any other questions.

thanks.

**Comment by sblantipodi** [comment]
@lroubinov if you want, you can follow the discussion here #31
