### ISSUE TITLE
[Feature request]: Configureable option to turn off built-in LED 

### ISSUE THREAD

**Issue by fleity** [sblantipodi/firefly_luciferin#55]

**Comment by sblantipodi** [comment]
@fleity the way you turn off built in LED depends on the microcontroller you use.
this can be very difficult to implement since Luciferin is meant for every ESP32/ESP8266 based boards.
Thank you for your feature request, at the moment I'll close it but I'll keep it in mind if I'll find a way to do it for every boards.

In the mean time, if it bugs you, you can simply desolder the LED from your board.
